### ISSUE TITLE
visual bug sub project's tasks

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#752]
after entering a sub project,and creating a new task for the sub project, the task's template won't open and instead the projects template would show up with everything but it's name, and top row options deleted

**Comment by nevos** [comment]
reiterate on description -  sub projects list has the following issues:
1. the title should be "Projects from project <parent project name>" 
1.a <parent project name> missing.
1.b says "project from task <...>" instead of projects from projects
2. in the subproject list - the items dont show, but they do show on the details pane.

**Comment by nevos** [comment]
sub tasks list entering a new subtask - from previous
