### ISSUE TITLE
documents editor permissions bug

### ISSUE THREAD

**Issue by AviramAshkenazi** [linnovate/root#879]
after a dding a partner to a document and changing his permissions to editor, the partner can change the details of the document but the changes aren't saved after refreshing the page

**Comment by nevos** [comment]
@AviramAshkenazi 
1) description not clear enough.
2) if you change someone elses permissions - they do not immediately reflect on the new user UI / browser.
3) if you change someones elses permissions - they **immediately** reflect on the new user permission set.

therefore, 
4) if the UI disables any activity until refresh - its OK.
5) if the UI ENABLES any activity that the new permission set disabled, that`s not OK. since this is not the case - the issue is closed (works as planned).
