### ISSUE TITLE
partner permissions bug

### ISSUE THREAD

**Issue by AviramAshkenazi** [linnovate/root#883]
after adding a partner to an entity and then setting him as an assignee, he still has the permissions of a watcher when he should have gotten the permissions of a commenter automatically when he got assigned as an assignee ( the partner still has the watcher permission after refreshing the page)

**Comment by nevos** [comment]
The idea is that assigning and un-assigning does not remove/update permissions that are already there. 
1) This was not clearly defined - what happens when someone is removed from being an assignee.
2)  What happens when someone is added as assignee after they are already a watcher.

Since this can be easily changed by the assigner - this issue will not be handled in 204.
@arbel - FYI
