### ISSUE TITLE
dev - fix console log

### ISSUE THREAD

**Issue by nevos** [linnovate/root#912]
there is something wrong with console usage. please fix.

**Comment by abrahamos** [comment]
This problem is caused by [`meanio`](https://github.com/linnovate/meanio/blob/e6f5d19edc674d7eb4959087f59ecf54d8aaa8ef/lib/notifiers.js#L84) (and was removed by version [`0.8.73`](https://github.com/linnovate/meanio/commit/0b8c24e7019c6f589737463aa1313379853865c5), at [this commit](https://github.com/linnovate/meanio/commit/c7bfbdbb01e9a185671f829dd7c99b1bd275f0f6))
I'm not sure how can we fix that.
